microsoft/vscode-azurestorage

- thirdpartynotices.txt
Adds fs-extra and copy-paste license informaion.
> Update third party notices.

- src/azureStroageExplorer/blobContainers/blobEditor.ts
- src/azureStroageExplorer/fileShares/directoryNode.ts
- src/azureStroageExplorer/fileShares/fileEditor.ts
- src/azureStroageExplorer/fileShares/fileNode.ts
- src/azureStroageExplorer/fileShares/fileShareNode.ts
Fixed editing files in folders.
Updated edit logic to use existing contentType.
> Fixed editing files in folders. Updated edit logic to use existing contentType.

- package.json
- src/azureStroageExplorer/blobContainers/blobContainerGroupNode.ts
- src/azureStroageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStroageExplorer/fileShares/fileShareGroupActionHandlers.ts
- src/azureStroageExplorer/fileShares/fileShareGroupNode.ts
- src/azureStroageExplorer/fileShares/fileShareNode.ts
- src/azureStroageExplorer/queues/queueActionHandlers.ts
- src/azureStroageExplorer/queues/queueGroupActionHandlers.ts
- src/azureStroageExplorer/queues/queueGroupNode.ts
- src/azureStroageExplorer/queues/queueNode.ts
- src/azureStroageExplorer/tables/tableActionHandlers.ts
- src/azureStroageExplorer/tables/tableGroupActionHandlers.ts
- src/azureStroageExplorer/tables/tableGroupNode.ts
- src/azureStroageExplorer/tables/tableNode.ts
- src/extension.ts
> Create and delete file shares, queues and tables, fixes #35

- package.json
- src/azureStroageExplorer/blobContainers/blobContainerGroupNode.ts
- src/azureStroageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStroageExplorer/fileShares/fileShareGroupActionHandlers.ts
- src/azureStroageExplorer/fileShares/fileShareGroupNode.ts
- src/azureStroageExplorer/fileShares/fileShareNode.ts
- src/azureStroageExplorer/queues/queueActionHandlers.ts
- src/azureStroageExplorer/queues/queueGroupActionHandlers.ts
- src/azureStroageExplorer/queues/queueGroupNode.ts
- src/azureStroageExplorer/queues/queueNode.ts
- src/azureStroageExplorer/tables/tableActionHandlers.ts
- src/azureStroageExplorer/tables/tableGroupActionHandlers.ts
- src/azureStroageExplorer/tables/tableGroupNode.ts
- src/azureStroageExplorer/tables/tableNode.ts
- src/extension.ts
This was already reviewed in a different branch.
> Create/delete file shares, tables, queues

- src/azureStorageExplorer/blobContainers/blobActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerGroupActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/directoryActionHandlers.ts
- src/azureStorageExplorer/fileShares/directoryUtils.ts
- src/azureStorageExplorer/fileShares/fileActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareGroupActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/loadMoreActionHandler.ts
- src/azureStorageExplorer/queues/queueActionHandlers.ts
- src/azureStorageExplorer/queues/queueGroupActionHandlers.ts
- src/azureStorageExplorer/queues/queueNode.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/tables/tableActionHandlers.ts
- src/azureStorageExplorer/tables/tableGroupActionHandlers.ts
- src/azureStorageExplorer/tables/tableNode.ts
- src/components/launcher/launcher.ts
- src/extension.ts
- src/storageExplorerLauncher/macOSStorageExplorerLauncher.ts
- src/storageExplorerLauncher/windowsStorageExplorerLauncher.ts
- tslint.json
> More lint cleanup

- package-lock.json
- package.json
- src/azureServiceExplorer/editors/RemoteFileEditor.ts
- src/azureStorageExplorer/blobContainers/blobActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobFileHandler.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/fileFileHandler.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStorageExplorer/limits.ts
- src/azureStorageExplorer/queues/queueActionHandlers.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/tables/tableActionHandlers.ts
- src/components/progress.ts
- src/storageExplorerLauncher/ResourceType.ts
- src/storageExplorerLauncher/macOSStorageExplorerLauncher.ts
- src/storageExplorerLauncher/windowsStorageExplorerLauncher.ts
@EricJizbaMSFT One issue... For upload, I've got it currently set up via createChild. But if the blob already exists and user chooses to overwrite, you end up with two nodes. So either I need to delete the original node before upload, or need to not use createChild, in which case I need to manually added a node, not sure how to do that.  Suggestions?
> Support text blob upload/download

- package.json
- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobFileHandler.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStorageExplorer/queues/queueActionHandlers.ts
- src/azureStorageExplorer/storageAccountProvider.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/tables/tableActionHandlers.ts
- src/extension.ts
There's been a few breaking changes since the last version used. I just did the minimum necessary to get us to the latest version. The biggest benefit is the "Report an issue" button on errors
> Update UI package to get 'Report an issue'

- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
> Open new blobs/files in editor

- package.json
Fixes #143, fixes #89, fixes #119
Groups:
navigation
2_create
3_download
5_cutcopypaste
7_modification
9_refresh
> Organize menus

- package.json
> Update to storage SDK 2.9 preview for $web support

- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
> Fix reversed condition

- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
> Refresh web containers before determining if hosting supported

- README.md
Removed the "we've moved" message and added a link to the deployment
tutorial on the VS Code site.
> Update readme with tutorial link.

- package.json
- src/azureServiceExplorer/editors/RemoteFileEditor.ts
- src/azureStorageExplorer/azureStorageOutputChannel.ts
- src/azureStorageExplorer/blobContainers/blobActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerGroupActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobFileHandler.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/directoryActionHandlers.ts
- src/azureStorageExplorer/fileShares/directoryNode.ts
- src/azureStorageExplorer/fileShares/directoryUtils.ts
- src/azureStorageExplorer/fileShares/fileActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileNode.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareGroupActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/loadMoreActionHandler.ts
- src/azureStorageExplorer/queues/queueActionHandlers.ts
- src/azureStorageExplorer/queues/queueGroupActionHandlers.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/tables/tableActionHandlers.ts
- src/azureStorageExplorer/tables/tableGroupActionHandlers.ts
- src/components/progress.ts
- src/components/telemetry/reporter.ts
- src/extension.ts
- src/extensionVariables.ts
- tslint.json
Based on these breaking changes in the ui package: https://github.com/Microsoft/vscode-azuretools/pull/208
> Pre-register extension variables with ui package

- package.json
See https://github.com/Microsoft/vscode-azuretools/pull/228 for more info
> Update to latest telemetry package

- package.json
Opens the Azure view with ctrl/cmd + shift + a
> Add shortcut key

- package-lock.json
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
> Add '/' in blobFriendlyPath.

- package-lock.json
- package.json
- src/azureStorageExplorer/storageAccounts/storageAccountNode.ts
Revert https://github.com/Microsoft/vscode-azurestorage/pull/280 and just leverage latest ui package instead. (There were breaking changes in the ui package, but it's a no-op for this repo)
> Leverage latest ui package

- src/azureStorageExplorer/blobContainers/quickPickUtils.ts
> Deploy static website: Show dist, out and build folders if they exist.

- package-lock.json
- src/azureStorageExplorer/fileShares/fileUtils.ts
> Add async validation on input to check if fileName exists

- package-lock.json
- package.json
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/storageAccounts/storageAccountNode.ts
> Allow user to delete storage account

- package-lock.json
- package.json
- src/azureStorageExplorer/storageAccountProvider.ts
- src/azureStorageExplorer/wizard/storageAccountCreateStep.ts
- src/azureStorageExplorer/wizard/storageAccountNameStep.ts
- src/extension.ts
Builds will fail till the corr. PR in azuretools is merged: https://github.com/Microsoft/vscode-azuretools/pull/395
Fixes #278
> Allow creating V2 accounts for Static websites

- .vscode/extensions.json
- .vscode/settings.json
> Update tslint extension

- package-lock.json
- package.json
- src/azureStorageExplorer/storageAccountProvider.ts
- src/azureStorageExplorer/wizard/storageAccountCreateStep.ts
- src/azureStorageExplorer/wizard/storageAccountNameStep.ts
- src/extension.ts
Mainly doing this to get storage up-to-date with the latest ui package, but that also means it'll benefit from the back button in the wizard.
> Leverage updated wizard with back button

- src/azureStorageExplorer/fileShares/FileShareFS.ts
> read file in file explorer

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/fileShares/FileShareFS.ts
> [blob] deleting virtual folders and files recursively

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/fileShares/FileShareFS.ts
> Edit blobs through file explorer

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/fileShares/FileShareFS.ts
> Progress notifications

- extension.bundle.ts
- package-lock.json
- package.json
- src/azureStorageExplorer/AzureAccountTreeItem.ts
- test/global.test.ts
- test/storageAccountActions.test.ts
Depends on https://github.com/microsoft/vscode-azuretools/pull/541
I moved `Test*` classes to the dev package instead of ui package
> Leverage latest UI and dev packages

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/fileShares/FileShareFS.ts
> Error shows up only once when moving/renaming

- package-lock.json
- package.json
- src/extensionVariables.ts
See https://github.com/microsoft/vscode-azuretools/pull/550 for more info
Breaking change in dev package doesn't affect this extension
> Update shared packages to fix icons

- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
Need to remove “await“ on "vscode.window.showinformationmessage" for deploy test cases.
> Need to remove “await“ on "vscode.window.showinformationmessage" for deploy test cases

- package-lock.json
- package.json
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/directoryNode.ts
- src/azureStorageExplorer/fileShares/fileNode.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- test/storageAccountActions.test.ts
> clipboardy -> vscode.env.clipboard

- src/azureStorageExplorer/blobContainers/blobContainerGroupNode.ts
- test/storageAccountActions.test.ts
1. Add create blob container test case and update vscode.windows to ext.ui.
2. Add a common method to simplify the code.
> Add create blob container test case

- src/azureStorageExplorer/fileShares/fileShareGroupNode.ts
- test/storageAccountActions.test.ts
Add create file share test case.
> Add create file share test case

- src/storageExplorerLauncher/macOSStorageExplorerLauncher.ts
- src/utils/workspaceUtils.ts
> Remove calls to vscode.workspace.rootPath

- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
> Ignore only .git and .vscode folders during deployment

- package-lock.json
- package.json
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/directoryNode.ts
- src/azureStorageExplorer/fileShares/fileNode.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
> Use vscode.env.clipboard

- package.json
- resources/dark/createStorageAccount.svg
- resources/light/createStorageAccount.svg
Fixes #306
Adds a plus button on the sash
> Add 'Create Storage Account' button to sash

- src/extension.ts
> Add "Collapse All" button

- package-lock.json
- package.json
- resources/dark/AzureStorageAccount.svg
- resources/light/AzureStorageAccount.svg
- src/azureStorageExplorer/SubscriptionTreeItem.ts
- src/extension.ts
- src/extensionVariables.ts
This pulls in the latest UI package.
Old:
New:
> Update icons 🔑

- src/azureServiceExplorer/editors/RemoteFileEditor.ts
- src/azureStorageExplorer/AzureStorageFS.ts
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobFileHandler.ts
- src/azureStorageExplorer/blobContainers/blobUtils.ts
- src/azureStorageExplorer/fileShares/fileFileHandler.ts
- src/azureStorageExplorer/fileShares/fileUtils.ts
> Make file/blob metadata & properties persistent after update

- src/azureStorageExplorer/queues/queueGroupNode.ts
- test/storageAccountActions.test.ts
> Add create queue test case

- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- test/storageAccountActions.test.ts
1. Add delete blob container test.
2. Add 'string' type definition for all the resource names (containerName, shareName, queueName, tableName).
> Add delete blob container test

- src/azureStorageExplorer/fileShares/fileShareNode.ts
- test/storageAccountActions.test.ts
> add delete file share test

- src/azureStorageExplorer/queues/queueNode.ts
- test/storageAccountActions.test.ts
> add delete queue test

- src/azureStorageExplorer/wizard/storageAccountCreateStep.ts
> Enable "Secure transfer required"  by default when creating storage accounts

- src/extension.ts
Since `registerCommand` takes care of that already.
> Remove extra `callWithTelemetryAndErrorHandling`

- src/azureStorageExplorer/blobContainers/BlobContainerGroupTreeItem.ts
- src/azureStorageExplorer/blobContainers/blobUtils.ts
- src/azureStorageExplorer/fileShares/directoryNode.ts
- src/azureStorageExplorer/fileShares/directoryUtils.ts
- src/azureStorageExplorer/fileShares/fileShareGroupNode.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/queues/queueGroupNode.ts
- src/azureStorageExplorer/tables/tableGroupNode.ts
- src/constants.ts
To ensure we're consistent and to make it easier when debugging things related to "Load More"
> Add a constant for maxPageSize

- package.json
- src/commands/blob/blobContainerActionHandlers.ts
- src/commands/fileShare/fileShareActionHandlers.ts
- src/utils/blobUtils.ts
- src/utils/fileUtils.ts
Fixes #186 
This honors the existing content type, if it exists.
> Don't ❌ default to text/plain content type 📝 when creating blobs and files 🗂

- src/AzureStorageFS.ts
Old:
New:
Fixes https://github.com/microsoft/vscode-azurestorage/issues/556
> Improve loading message

- src/AzureStorageFS.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/fileShare/FileTreeItem.ts
- src/utils/nonNull.ts
I tested it out as described here: https://github.com/microsoft/vscode-azurestorage/issues/435#issuecomment-571783555
Fixes https://github.com/microsoft/vscode-azurestorage/issues/435
> Add support for watch 👀

- src/tree/blob/BlobTreeItem.ts
Related: https://github.com/microsoft/vscode-azurestorage/pull/558#discussion_r365377708
> Don't decode blob URLs

- package.json
- src/AzureStorageFS.ts
- src/constants.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/351
> Remove 'enableViewInFileExplorer' feature flag 🚩

- package-lock.json
- package.json
> Pull up 🆙☝️ UI

- src/AzureStorageFS.ts
For an invalid `folders.url` (created by removing the blob container name), `lookupRoot` is called many times for all the URIs present. Each time, an error would be thrown since the root `BlobContainerGroupTreeItem` didn't exist.
This fix displays only one `lookupRoot` error per `rootName`
Fixes #546
> Fix multiple errors for invalid folders.url

- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/blobUtils.ts
> Display new nested blob names properly

- package.json
> Remove showSavePrompt

- package.json
Fixes https://github.com/microsoft/vscode-azurestorage/issues/359
> Add refresh command to cmd palette 

- package.json
Fixes https://github.com/microsoft/vscode-azurestorage/issues/272
> Update 'delete' labels

- package.json
- src/commands/uploadToAzureStorage.ts
- src/extension.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/blob/BlobContainerGroupTreeItem.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareGroupTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/queue/QueueGroupTreeItem.ts
- src/tree/table/TableGroupTreeItem.ts
- src/utils/directoryUtils.ts
- src/utils/errorUtils.ts
- src/utils/fs.ts
- src/utils/uploadUtils.ts
- src/utils/workspaceUtils.ts
This adds support for uploading folders only
Related to https://github.com/microsoft/vscode-azurestorage/issues/159
Addresses comments from https://github.com/microsoft/vscode-azurestorage/pull/588
> Add 'Upload to Azure Storage...' command

- src/commands/api/revealTreeItem.ts
- src/extension.ts
- src/vscode-azurestorage.api.d.ts
To be used by resource groups extension
> Add revealTreeItem api

- src/tree/blob/BlobContainerTreeItem.ts
Use `TransferProgress` instead of the old progress logic.
This implements the remaining changes from https://github.com/microsoft/vscode-azurestorage/pull/588
> Refactor 'deploy to static website'

- src/AzureStorageFS.ts
- src/commands/blob/blobContainerActionHandlers.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/blobUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/601
Fixes https://github.com/microsoft/vscode-azurestorage/issues/574
> Create blobs & directories manually in 'createBlockBlob'

- package.json
- src/commands/uploadToAzureStorage.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/159
> Support file uploads in 'Upload to Azure Storage...'

- src/tree/StorageAccountTreeItem.ts
Old
New
Fixes https://github.com/microsoft/vscode-azurestorage/issues/569
> Add storage account name to the update static site config notification

- src/tree/blob/BlobDirectoryTreeItem.ts
Old/new
Fixes https://github.com/microsoft/vscode-azurestorage/issues/600
> Fix blob directory layout in Azure view

- src/tree/StorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/567
> Add log message and notification when deleting storage account

- src/commands/blob/blobActionHandlers.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/limits.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/87
> Add telemetry for uploading/downloading blobs

- src/tree/StorageAccountTreeItem.ts
Fixes #629 
Fixes #336 
The connection string requires an endpointSuffix in order to connect via Will's PR: https://github.com/microsoft/vscode-azurestorage/pull/618
> Add endpoint suffix to the connection string

- src/utils/uploadUtils.ts
Old
New
Fixes https://github.com/microsoft/vscode-azurestorage/issues/639
Fixes https://github.com/microsoft/vscode-azurestorage/issues/640
> Update 'Upload to Azure Storage...' log messages

- CHANGELOG.md
- NOTICE.html
- README.md
- package-lock.json
- package.json
I generated the notice from [this branch](https://github.com/microsoft/vscode-azurestorage/tree/wwl/local-emulator) to pull in keytar
> Prep for 0.9.0

- test/storageAccountActions.test.ts
> Fix tests after adding support for attached accounts

- .azure-pipelines/common/build.yml
- package-lock.json
- package.json
- src/utils/cpUtils.ts
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2103
> Bump min version of VS Code to 1.40.0 and Node.js to 12.0.0

- src/TransferProgress.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/tree/createWizard/storageAccountCreateStep.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/fileShare/FileTreeItem.ts
- src/utils/directoryUtils.ts
- src/utils/progress.ts
- src/utils/uploadUtils.ts
Fixes #678 
I changed occurances of `appendLine` with `appendLog`
> Use appendLog instead of appendLine

- package.json
- src/commands/blob/blobContainerActionHandlers.ts
- src/commands/uploadFile.ts
- src/extension.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/limits.ts
Support uploading file share files as well as blobs
Fixes https://github.com/microsoft/vscode-azurestorage/issues/713
> Rename `uploadBlockBlob` ➡️  `uploadFile`

- src/commands/uploadFile.ts
- src/utils/uploadUtils.ts
A lot of these smaller PRs will be preparing for AzCopy changes
> Add function 'warnFileAlreadyExists'

- gulpfile.ts
- package-lock.json
- package.json
- src/commands/openInFileExplorer/OpenTreeItemStep.ts
- src/tree/AttachedStorageAccountsTreeItem.ts
- src/tree/IStorageRoot.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
- src/tree/createWizard/StorageAccountTreeItemCreateStep.ts
- src/tree/createWizard/storageAccountCreateStep.ts
- src/tree/createWizard/storageAccountNameStep.ts
- src/utils/storageWrappers.ts
- test/nightly/global.resource.test.ts
- test/nightly/storageAccountActions.test.ts
- test/runTest.ts
Means people (aka us) will have to use VS Code insiders until 1.48 goes stable
> Update to new azure-sdk-for-js

- src/utils/validateNames.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/719
> Rename 'Filename' to 'File name' in prompts

- src/commands/uploadToAzureStorage.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/764
> Add output logs when uploading folder via uploadToAzureStorage

- src/commands/uploadToAzureStorage.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/763
| Old | New |
|-|-|
|<img width="648" alt="old1" src="https://user-images.githubusercontent.com/22795803/92146692-ed63ad80-edce-11ea-8c84-5af4a5d1d452.png">| <img width="648" alt="new1" src="https://user-images.githubusercontent.com/22795803/92146794-15eba780-edcf-11ea-8fd9-a219a00290dd.png">|
> Make log and notification consistent when uploading single file

- src/commands/uploadToAzureStorage.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/uploadUtils.ts
- src/utils/workspaceUtils.ts
Related to https://github.com/microsoft/vscode-azurestorage/issues/685
I'll add context menu items to better expose this functionality in a different PR
> Support uploading multiple files/folders via uploadToAzureStorage

- src/commands/azCopy/azCopyLocations.ts
- src/commands/azCopy/azCopyTransfer.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/limits.ts
- src/utils/uploadUtils.ts
Related to https://github.com/microsoft/vscode-azurestorage/issues/755
> Use AzCopy for blob downloads

- package.json
- src/commands/azCopy/azCopyLocations.ts
- src/commands/blob/blobActionHandlers.ts
- src/commands/downloadFile.ts
- src/extension.ts
- src/tree/blob/BlobTreeItem.ts
This adds support for downloading single files and fixes https://github.com/microsoft/vscode-azurestorage/issues/755
> Refactor downloadBlob into downloadFile

- src/commands/uploadToAzureStorage.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/771
> Automatically show resources in tree view after 'Upload to Azure Storage...' upload

- src/commands/uploadFiles.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/803
> Ignore directory uploads in uploadFiles

- src/commands/selectStorageAccountNodeForCommand.ts
- src/extension.ts
- src/tree/StorageAccountTreeItem.ts
🚫 "Only general purpose V2 storage accounts support static website hosting."
> Suppress report issue for V2 storage account error

- src/commands/uploadFiles.ts
- src/commands/uploadToAzureStorage.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/807
> Don't show uploading message for 'no overwrite' case

- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/813
> Fix 'No to all' overwrite behavior when uploading

- src/TransferProgress.ts
- src/commands/downloadFile.ts
- src/commands/uploadToAzureStorage.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/806
> Add punctuation and units to AzCopy transfers

- src/commands/uploadFiles.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/814
> Add destination directory prompt when uploading blobs/files

- src/commands/uploadToAzureStorage.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/805
> Prevent double-upload when a folder and its contents are selected

- src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/671
> Remove duplicate notification when creating a storage account

- CHANGELOG.md
- package-lock.json
- package.json
NOTICE.html was already up to date.
> Prep for 0.10.1 🎃

- src/commands/uploadToAzureStorage.ts
This checks for child files/folders against the list of *all* folder URIs selected. I also moved the `shouldUploadUri()` call to make sure we aren't prompting to overwrite resources that won't actually be uploaded.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/830
> Refactor uploadToAzureStorage to prevent child uploads when the parent upload is cancelled

- package.json
- src/commands/blob/blobActionHandlers.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/795
> Add "Copy URL" and "Delete..." context menu items for blob directories

- src/commands/azCopy/azCopyTransfer.ts
`handleFinalTransferStatus` and `startAndWaitForTransfer` can be reused for deleting.
I organized `src` and `dst` into `ITransferLocation` and I'll add a `IDeleteLocation` in a different PR which will just have a single location associated with it for deletions
> Revise `azCopyTransfer` to make implementing delete easier

- src/AzureStorageFS.ts
- src/commands/blob/blobContainerActionHandlers.ts
- src/commands/fileShare/fileShareActionHandlers.ts
- src/constants.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/666 😈
> Throw a better error when trying to edit a blob/file larger than 50MB

- src/commands/uploadFiles.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/utils/uploadUtils.ts
Related to https://github.com/microsoft/vscode-azurestorage/issues/788
> Refactor `shouldUploadUri` to be useful for multi-downloads

- package.json
This also consolidates azure subscription context items
Fixes https://github.com/microsoft/vscode-azurestorage/issues/491
> Add "Open in Portal" to Azure subscription tree item

- src/utils/checkCanOverwrite.ts
- src/utils/uploadUtils.ts
The only other change is to this string:
```A resource named "{0}" already exists. Do you want to upload and overwrite it?```
⬇️
```A resource named "{0}" already exists. Do you want to overwrite it?```
> Move checkCanOverwrite to its own file

- src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/845
> Register Microsoft.Storage provider

- src/commands/azCopy/azCopyTransfer.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/818
> Link to AzCopy log file in the output window for failed/skipped transfers

- src/tree/blob/BlobDirectoryTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/846
> Add delete confirmation message for blob directories

- src/commands/downloadFile.ts
- src/extension.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/788
> Support downloading multiple blobs, files, and directories

- package.json
- src/constants.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/utils/settingsUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/524
> Add delete before deploy setting

- package-lock.json
- package.json
- src/commands/detachStorageAccount.ts
- src/commands/startEmulator.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/extension.ts
- src/tree/AttachedStorageAccountsTreeItem.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/createWizard/StaticWebsiteConfigureStep.ts
Related to https://github.com/microsoft/vscode-azuretools/pull/820
> Bump UI package

- package.json
- src/extension.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/140
Fixes https://github.com/microsoft/vscode-azurestorage/issues/887
> Don't show 'Open in Storage Explorer' menu item on Linux or Codespaces

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/748
> Shift editor focus to blobs/files opened from the Azure view

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/632
> Populate ctime, mtime, and size in AzureStorageFS.stat

- src/AzureStorageFS.ts
- src/utils/directoryUtils.ts
- src/utils/fileUtils.ts
- src/utils/validateNames.ts
This also combines name validation logic for files and directories because it's so similar
Fixes https://github.com/microsoft/vscode-azurestorage/issues/848
> Check new file/directory names against existing resources

- src/tree/blob/BlobDirectoryTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/910
> Add ellipses to 'Deleting directory' message

- src/commands/uploadFiles.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/772
> Add info message & output log for successful uploads

- src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/749
> Add 'Load more' for storage accounts

- package-lock.json
- package.json
- src/TransferProgress.ts
- src/commands/azCopy/azCopyTransfer.ts
- src/commands/downloadFile.ts
- src/commands/uploadFolder.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/uploadUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/873
> Always use AzCopy to get total resources to upload

- package.json
- src/extension.ts
> Use "Report Issue" command

- src/tree/createWizard/storageAccountNameStep.ts
Related to https://github.com/microsoft/vscode-azuretools/pull/824
> Use valuesToMask for storage account name

- .vscode/extensions.json
- README.md
Already did it in most repos yesterday, just not the first two.
> Add resource groups extension to recommended for workspace

- package-lock.json
- package.json
> Bump to next alfalfa

- package-lock.json
- package.json
- src/utils/azureClients.ts
Hey @ejizba, just update arm-storage package to profile-2020-09-01 to the latest one we are supporting and keep it consistent with resource group. Will keep an eye on it next time to keep package used by every extension consistent and be updated to latest version.
> Update arm-storage-profile-2019-03-01-hybrid package to arm-storage-profile-2020-09-01-hybrid

- package-lock.json
- package.json
- src/constants.ts
- src/tree/SubscriptionTreeItem.ts
- src/tree/createWizard/storageAccountCreateStep.ts
and `npm audit fix`
The breaking changes in the UI package from v0.41 to v0.43 were related to better location filtering in the location step.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/892
> Update UI package

- package-lock.json
- package.json
- src/commands/storageAccountActionHandlers.ts
Depends on https://github.com/microsoft/vscode-azuretools/pull/999
> Set eventVersion to 2 for a few events

- package-lock.json
- package.json
- src/tree/SubscriptionTreeItem.ts
- src/tree/createWizard/storageAccountCreateStep.ts
Depends on https://github.com/microsoft/vscode-azuretools/pull/1034
Edge zones only support premium storage accounts, so I added this to the description of edge zone locations in the LocationListStep.
> Edge zone support

- src/tree/StorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1048
> Fix delete activity title

- package-lock.json
- package.json
- src/StorageWorkspaceProvider.ts
- src/extension.ts
> Set ext.attachedStorageAccountsTreeItem on activation

- package-lock.json
- package.json
- src/commands/createStorageAccount.ts
In response to: https://github.com/microsoft/vscode-azurestorage/issues/989
> Made location prompting on storage creation a default step. Id #989

- package-lock.json
- package.json
- src/tree/StorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1040
> Use fullid and ensure that children are loaded before trying to find tree item

- src/commands/startEmulator.ts
- src/extension.ts
- src/tree/AttachedStorageAccountTreeItem.ts
- src/tree/table/TableGroupTreeItem.ts
> Add support for emulated tables

- src/AzureStorageFS.ts
Fixes #1065
Following what we do here:
https://github.com/microsoft/vscode-azurestorage/blob/2be53ebb91f130763f081e8a87e62f5bcf40218b/src/AzureStorageFS.ts#L460-L462
> Fix opening a file from an attached account

- package.json
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
> Renamed "Open in File Explorer" command to "Open in Explorer" 

- src/tree/blob/BlobDirectoryTreeItem.ts
Fixes #1028 and potentially #982
> Fix folder deletion in blob containers so all files get deleted

- src/StorageAccountResolver.ts
Fixes #1120 
Also cleaned up this file
> Mark resolveResource as an activation event

- package.json
See https://github.com/microsoft/vscode-azureresourcegroups/pull/366#discussion_r951755858 for context
> Use new AzExtResourceType context values

- src/utils/directoryUtils.ts
- src/utils/fs.ts
- src/utils/uploadUtils.ts
> Fixed empty folder not showing in file share once uploaded

- src/tree/queue/QueueGroupTreeItem.ts
- src/tree/table/TableGroupTreeItem.ts
- src/utils/directoryUtils.ts
- src/utils/uploadUtils.ts
> Added error message when creating queue/tables with existing name

- src/AzureStorageFS.ts
Fixes #1132. Not sure if this is how we would want to do it but this is the only thing I found that could get rid of those error messages. Also takes takes care of the error message seen in #1136.
> Fixes error messages when opening blob in explorer

- src/commands/blob/blobContainerActionHandlers.ts
> Fixed creating an empty blob with name "a/b/file01"

- package.json
> Hide SAS Url command from palette

- src/tree/blob/BlobTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1142
> Make blob lowercase

- src/commands/uploadFiles/UploadFilesStep.ts
Fixes #1143. I modeled this change after UploadLocalFolder. Not sure if we would want to do it this way but it does solve the issue.
> Fixed file uploaded to existing directory showing up in the wrong place

- src/commands/downloadFile.ts
> Fixed downloading an empty file share/blob container to selected destination

- src/tree/fileShare/FileShareGroupTreeItem.ts
- src/tree/fileShare/createFileShare/FileShareNameStep.ts
- src/tree/fileShare/createFileShare/IFileShareWizardContext.ts
- src/tree/fileShare/createFileShare/StorageQuotaPromptStep.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1147
> Refactor createFileShare into wizard prompt steps

- package.json
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/375
> Fix context values for storage account create

- src/tree/table/TableGroupTreeItem.ts
- src/utils/storageWrappers.ts
Just doing some post-release cleanup. This also takes us one step closer to enabling "strict". This file is now complies with "strict".
> Remove extra nonNull util

- package-lock.json
- package.json
- src/extension.ts
- webpack.config.js
Splitting out these changes that were required in #1227 into a new PR
> Update shared packages and vscode engine

- src/AzureStorageFS.ts
- src/BlobContainerFS.ts
Add progress notifications to the new blob fs just like the old one had. The notifications are shown when creating/saving/deleting blobs.
> Add notifications to new blob fs

- src/BlobContainerFS.ts
> Add nice error when creating directories is not supported

- package.json
Working towards https://github.com/microsoft/vscode-azureresourcegroups/issues/673
> Add actions submenu to workspace view title

- .azure-pipelines/common/package.yml
- package.json
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1267
> Add icon paths to fix light theme

- src/commands/transfers/transfers.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1262#issuecomment-2149277785
> Look at type when setting azCopyTransfer parameter

- src/StorageAccountResolver.ts
Copying over the improvement we've done in a few other extensions https://github.com/microsoft/vscode-azureappservice/pull/2542
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1218
> Cache a list operation to speed up resolving

- package-lock.json
- src/StorageAccountResolver.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1314
Mostly at least. The condition about the `provisionState` fixes the creating multiple at once error.
Deleting several at once will still error sometimes, but since the error isn't being thrown, it's not as obvious. It will be fixed when the refresh happens (that was triggered by the delete). But the shortened cache makes the issue less frequent.
> Shorten the cache time because it was causing stale data

- src/StorageAccountResolver.ts
In effort to fix: https://github.com/microsoft/vscode-azurestorage/issues/1329
> Add a listTask so the cache works for all resolves

- package-lock.json
- package.json
- src/AttachedAccountRoot.ts
Includes the new telemetry updates
> Upgrade utils and dev package

- gulpfile.ts
> Fix file permissions for some AzCopy dependencies

- .github/workflows/main.yml
Partially addresses #1346 
Feel free to test with the run artifacts here: https://github.com/microsoft/vscode-azurestorage/actions/runs/12417276989
> Set AzCopy permissions for GitHub workflows

- .vscode/settings.json
- src/utils/directoryUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1393
Honestly, we may not even want either of these to show up in the activity log, but I figured that we can revisit that later and just make it consistent for now.
> Delete file share directory execute step

- package-lock.json
- package.json
- src/StorageAccountResolver.ts
- src/commands/selectStorageAccountNodeForCommand.ts
- src/commands/storageAccountActionHandlers.ts
- src/tree/AttachedStorageAccountTreeItem.ts
- src/tree/IStorageRoot.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/blob/BlobContainerGroupTreeItem.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/createWizard/StorageAccountTreeItemCreateStep.ts
- src/utils/storageWrappers.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1401
> Refactor storage accounts to load on expand and use ARM graph

- .vscode/extensions.json
- CHANGELOG.md
- package-lock.json
- package.json
- test/runTest.ts
Also removed stray dependencies/recommendations on the azure-account extension.
> Version bump, changelog
