- src/storageExplorerLauncher/windowsStorageExplorerLauncher.ts
These show up as Chinese in vscode, causing parse errors in the editor.
> Remove misc characters in code

- package.json
This repo isn't directly using the wizard, but I want to make sure it stays up to date
> Bump ui package version due to breaking changes in wizard

- package.json
There were breaking changes to the UI package, but nothing affecting this extension.
> Update ui package to latest breaking changes

- package.json
- src/extension.ts
Fixes #105 
@EricJizbaMSFT It's possible to get a link to a blob container via a URL like this:
https://ms.portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2<SUBID>%2FresourceGroups%2F<RESOURCE GROUP>%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%<STGACCT>/path/<BLOBCONTAINER>
I have no idea if this is safe to take a dependency on, do you know?  Thx.
> Open in portal for storage accounts

- package.json
- src/azureStorageExplorer/storageAccountProvider.ts
There were some recent breaking changes in the ui package related to sovereigns in the wizardContext, but I guess this repo doesn't use those wizards.
Fixes #217
> Add support for sovereigns

- package.json
This repo is already using createTelemetryReporter from the shared package so there's no need to have the direct dependency here.
Fixes #242
> Remove direct dependency on telemetry package

- .gitignore
- package.json
See here for discussion: https://github.com/Microsoft/vscode-azurestorage/pull/183#discussion_r198285619
These have been "ungrouped" for a few months now and with several releases coming up it feels like a good time to fix this:
> Group deploy commands together

- package-lock.json
- package.json
- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
- src/azureStorageExplorer/blobContainers/blobNode.ts
- src/azureStorageExplorer/fileShares/directoryNode.ts
- src/azureStorageExplorer/fileShares/fileNode.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- thirdpartynotices.txt
Note: The npm install here also updated a few other packages.  
Fixes https://github.com/Microsoft/vscode-azurestorage/issues/141
> copy-paste -> clipboardy

- README.md
- package.json
- src/azureStorageExplorer/blobContainers/quickPickUtils.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/components/fs.ts
- src/constants.ts
Fixes https://github.com/Microsoft/vscode-azurestorage/issues/216
This was another piece of low-hanging fruit I thought I'd stick in the next release. Basically copied all of this logic from functions/app service which already support a `preDeployTask`.
> Add preDeployTask setting

- .vscode/settings.json
- package.json
- src/azureStorageExplorer/blobContainers/blobContainerActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerGroupActionHandlers.ts
- src/azureStorageExplorer/blobContainers/blobContainerGroupNode.ts
- src/azureStorageExplorer/commonTreeCommands.ts
- src/azureStorageExplorer/fileShares/fileShareActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareGroupActionHandlers.ts
- src/azureStorageExplorer/fileShares/fileShareGroupNode.ts
- src/azureStorageExplorer/fileShares/fileShareNode.ts
- src/azureStorageExplorer/queues/queueActionHandlers.ts
- src/azureStorageExplorer/queues/queueGroupActionHandlers.ts
- src/azureStorageExplorer/queues/queueGroupNode.ts
- src/azureStorageExplorer/queues/queueNode.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
- src/azureStorageExplorer/storageAccounts/storageAccountNode.ts
- src/azureStorageExplorer/tables/tableActionHandlers.ts
- src/azureStorageExplorer/tables/tableGroupActionHandlers.ts
- src/azureStorageExplorer/tables/tableGroupNode.ts
- src/azureStorageExplorer/tables/tableNode.ts
- src/extension.ts
I thought I'd knock out some low-hanging fruit for the next release of Storage. This turned out to affect more files than I originally thought it would, but still very simple/tedious work.
1. Adds command palette support for top levels of tree. I did not add support for any commands below queue/table/file share/blob container. Fixes a lot of #221
1. Standardize use of ellipses in command name based on [these rules](https://docs.microsoft.com/en-us/windows/desktop/uxguide/cmd-menus#using-ellipses)
> Add support for command palette

- package.json
- src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts
- src/azureStorageExplorer/storageAccounts/storageAccountActionHandlers.ts
Fixes #305, #303 
- selectStorageAccountTreeItemForCommand: Actually _return_ the treeItem once we configure the account for static websites. 
- Rename "Delete Account..." to "Delete Storage Account..." to maintain consistency with "Create Storage Account"
> Fixes for CTI bugs

- src/azureStorageExplorer/storageAccounts/storageAccountNode.ts
The timeout errors arise due to the lack of retries in blobService. 
Repro: 
```
npx create react-app my-react-app
cd my-react-app
npm install
```
Deploy the entire app, then deploy it again and choose yes to delete all files
Fixes #352 
Fixes  #345 
Fixes  #370 
Fixes #334 
Fixes #340 
Fixes #338 
Fixes #339 
Fixes #342
Fixes #317
Fixes #362
> Add retryPolicy on creating services (blob/queue/fileshare/table)

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/fileShares/FileShareFS.ts
- src/azureStorageExplorer/showRenameError.ts
Fixes #419 #420 
The FileShareProvider deals with errors thrown by renaming and moving file/folders differently. To accommodate this, I differentiate between rename and move by comparing the basename and throw errors differently. 
Known: If I rename a folder/file such that the folder/file would be moved to a different location, no error message is shown. For example, if there exists a folder and file b at the same location, if I rename file b to be a/b, the UI will not change and the file's location will remain the same but no error message will be shown. For now, I will leave this as is.
> Differentiate between rename and move in File Share and Blob Container files

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
> 'View Output' button that directs to output channel when deleting blob folder

- src/azureStorageExplorer/blobContainers/blobContainerNode.ts
Fixes #454 
`context.childType` wasn't guaranteed to be defined for the 'create empty text blob' scenario
> Fix creating empty text blobs

- src/azureStorageExplorer/blobContainers/BlobContainerFS.ts
- src/azureStorageExplorer/parseUri.ts
Fixes #455
The trailing `/` led to the parent tree item not being found in file creation due to different expectations for trailing slashes.
> Ignore trailing slash in parentDirPath when parsing URIs

- src/azureStorageExplorer/queues/queueGroupNode.ts
- src/azureStorageExplorer/tables/tableGroupNode.ts
Fixes #482
Duplicate table: 
No error message was originally displayed for a duplicate queue.
> Make error message for duplicate tables/queues consistent

- package-lock.json
- package.json
Fixes #525
The new [@azure/storage-blob SDK](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob) introduced a dependent package ([node-fetch](https://github.com/bitinn/node-fetch)). With our existing webpack config, the package was minified in a way that caused the type check failure in this issue. Preventing function names from being mangled fixed the issue.
> Pull up ⬆️ dev 👩‍💻

- src/editors/BlobFileHandler.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/utils/blobUtils.ts
An alternative to this approach would be to suppress notifications if `suppressLogs` is true. But this implementation seemed cleaner and returns us to the old functionality before the SDK update.
Fixes #536
> Don't display progress notifications when uploading blobs

- src/commands/commonTreeCommands.ts
- src/tree/SubscriptionTreeItem.ts
First, advanced create should be an option wherever basic create is an option
Second, neither create option should be there when running a delete command
Fixes https://github.com/microsoft/vscode-azurestorage/issues/543
> Fix display of "Create Storage Account" for command palette

- package-lock.json
- package.json
- src/AzureStorageFS.ts
As far as I can tell, the `FileSystemProvider` api was not designed with pagination in mind (leading to problems like https://github.com/microsoft/vscode-azurestorage/issues/436). I'm not convinced pagination is a good fit for this scenario anyways, so I don't want to push VS Code to change anything yet. As discussed offline - we will load all resources (with a "cancel" button) and revisit this based on feedback if necessary.
Depends on https://github.com/microsoft/vscode-azuretools/pull/640
Fixes https://github.com/microsoft/vscode-azurestorage/issues/398
Fixes https://github.com/microsoft/vscode-azurestorage/issues/436
> Load all resources in AzureStorageFS

- package-lock.json
- package.json
- src/commands/selectStorageAccountNodeForCommand.ts
- src/commands/storageAccountActionHandlers.ts
- src/extension.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
1. No longer prompt to confirm 'enable website hosting' before configuring static website regardless of the entry point. If someone chooses to browse to or deploy their site, they likely want to enable website hosting.
2. When creating a storage account via basic create, immediately configure it for static website hosting with defaults. Default index document and error document: `index.html`
Fixes #505 
Fixes #544
> Improve static website configuration experience

- src/AzureStorageFS.ts
- src/editors/BlobFileHandler.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/blobUtils.ts
The file system loads all blobs, but `getBlob` only ever loads the first batch. That means if you're unlucky enough to edit a file in a later batch, you'll see this error:
We don't actually need `BlobItem` on `BlobTreeItem ` or `BlobPrefix` on `BlobDirectoryTreeItem `, so I just removed `getBlob` and cleaned up the code a bit.
> Remove `getBlob` because it doesn't work outside the first batch

- src/tree/blob/BlobTreeItem.ts
I used the wrong client when I originally implemented this. It turns out the issue with decoding URLs for nested files & directories is present for blobs too.
Fixes #560
> Fix copying blob URLs

- package-lock.json
- package.json
- src/AzureStorageFS.ts
- src/commands/fileShare/fileShareActionHandlers.ts
- src/editors/FileFileHandler.ts
- src/tree/IStorageRoot.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/tree/fileShare/FileShareGroupTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/fileShare/FileTreeItem.ts
- src/utils/directoryUtils.ts
- src/utils/fileUtils.ts
- test/storageAccountActions.test.ts
> Update ⬆️ to newest Azure Storage SDK for file shares 🗂

- src/AzureStorageFS.ts
- src/utils/directoryUtils.ts
- src/utils/validateNames.ts
This prevents nested directories for files or blobs from being created with the `\` separator. Backslashes are avoided because of [this problem](https://github.com/microsoft/vscode-azurestorage/issues/442#issuecomment-574930762) and because behavior is different between VS Code on Windows & Mac for `\` separators.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/442
> Create nested directories with '/' in file explorer

- src/editors/RemoteFileEditor.ts
Old error:
New error:
Fixes #583
> Add better error message when saving a file

- src/AzureStorageFS.ts
Actually fixes https://github.com/microsoft/vscode-azurestorage/issues/576
> Allow trailing slashes for directories, not for files/blobs

- src/editors/BlobFileHandler.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/utils/blobUtils.ts
This lets us use `TransferProgress` for more than just single blob transfers
Related to #159
> Make TransferProgress more portable

- src/AzureStorageFS.ts
There were multiple messages on insiders only. I assume the change on VS Code's side is intended & will makes its way to stable soon
Fixes https://github.com/microsoft/vscode-azurestorage/issues/596
> Fix multiple rename errors

- src/commands/storageAccountActionHandlers.ts
If static sites aren't enabled for the selected storage account, it prompts to configure without ending the deploy process.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/187
> Prompt for folder before storage account when deploying

- package.json
- src/tree/blob/BlobContainerTreeItem.ts
This changes the external facing 'block blob' verbiage to 'file'. I also removed the text file filter when selecting files to upload since it sounds like it was not helpful.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/687
> Refactor 'Upload Block Blob...' command

- package.json
Here's the new title: 
This title is kinda long... But it's descriptive. Open to more opinions on this one. 
Fixes https://github.com/microsoft/vscode-azurestorage/issues/695
> Make 'Deploy to Static Website...' command title less ambiguous

- src/extension.ts
For "Open in File Explorer...": Opening in current window or adding to workspace produced the same error, so always open in a new window.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/646
> Always open in new window for emulated storage accounts

- src/commands/blob/blobContainerActionHandlers.ts
- src/commands/uploadFile.ts
- src/tree/blob/BlobContainerTreeItem.ts
I'm planning to refactor `uploadBlockBlob` to work with file shares too. 
Related to https://github.com/microsoft/vscode-azurestorage/issues/713
> Move uploadBlockBlob & checkCanUpload to a new file

- src/TransferProgress.ts
I noticed this when implementing AzCopy stuff (which is coming soon 🤑)
> Only report transfer progress if some progress happened

- package.json
- src/tree/AttachedStorageAccountTreeItem.ts
- src/tree/IStorageRoot.ts
- src/tree/StorageAccountTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/fileUtils.ts
When onboarding the new SDK, file uploads for empty files would hang indefinitely so we reverted to the old SDK for those few special cases. [That issue](https://github.com/Azure/azure-sdk-for-js/issues/6904) was fixed in v12.1.1 of the new SDKs. I only ran into the problem for file shares but it looks like they shipped a [similar fix](https://github.com/XiaoningLiu/azure-sdk-for-js/commit/269aeeb117334a173b505bda2f28a4abd76bf3a9#diff-1ac4ced9d9574e91d2b0b5da1658680dR6) for blobs, so I bumped both SDK versions here.
> Remove references to old file share SDK

- src/commands/blob/blobContainerActionHandlers.ts
- src/utils/blobUtils.ts
- src/utils/fileUtils.ts
I plan on using these prompts in `uploadToAzureStorage` for single file uploads. `value` was added as a parameter so that the existing file name can be pre-filled.
I was running into problems where an invalid name (in the case of file shares) was causing the upload to fail. This prevents invalid names from being accepted.
> Update file name & blob path prompts

- src/tree/StorageAccountTreeItem.ts
I looked into why https://github.com/microsoft/vscode-azurestorage/issues/740 was happening and didn't find any clear answers in the ui package. The bug seems pretty inconsequential though because just adding a title prevents it.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/740
> Add configure static website wizard title

- src/commands/azCopy/azCopyTransfer.ts
- src/tree/blob/BlobContainerTreeItem.ts
We no longer need additional error handling when calling `azCopyTransfer`.
Also, `finalTransferStatus?.FailedTransfers` tends to be `[]` instead of null so not explicitly checking the length led to failed transfers being output when there were none.
Here's an example of errors for the same failed file transfer:
| Old  | New  |
|---|---|
| <img width="605" alt="Screen Shot 2020-09-02 at 2 08 14 PM" src="https://user-images.githubusercontent.com/22795803/92037287-66f39100-ed26-11ea-8c96-7f448ed6bc97.png">  | <img width="605" alt="Screen Shot 2020-09-02 at 2 07 11 PM" src="https://user-images.githubusercontent.com/22795803/92037278-62c77380-ed26-11ea-9a59-c159669c8723.png">  |
> Remove unneeded error handling & fix failed/skipped transfers listing

- package.json
- src/TransferProgress.ts
- src/commands/azCopy/azCopyTransfer.ts
- src/commands/uploadFile.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/constants.ts
- src/extension.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/createWizard/StaticWebsiteConfigureStep.ts
- src/tree/createWizard/storageAccountCreateStep.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/fileUtils.ts
- src/utils/uploadUtils.ts
I dialed back the functionality from https://github.com/microsoft/vscode-azurestorage/pull/760 to match what storage explorer does.
This keeps the code simpler and still lets users upload whatever combo of files/folders they need to. (If you want to upload multiple folders you can upload one folder containing all the other folders you want to upload)
Fixes https://github.com/microsoft/vscode-azurestorage/issues/623 once and for all 😤
> Split 'uploadToAzureStorage' into 'uploadFiles' and 'uploadFolder'

- package.json
- src/TransferProgress.ts
- src/commands/azCopy/azCopyLocations.ts
- src/commands/azCopy/azCopyTransfer.ts
- src/commands/downloadFile.ts
- src/extension.ts
There wasn't a good way to get how many children a blob directory or file directory has. So I modified `TransferProgress` to not take `totalWork` as a required parameter. Instead, AzCopy gives us that info during the transfer. Directory downloads will display a "?" for the initial total work and percentage until AzCopy reports that info (it takes about a second before that happens).
Fixes https://github.com/microsoft/vscode-azurestorage/issues/756
> Support directory downloads

- src/commands/azCopy/azCopyLocations.ts
The path used in `createAzCopyRemoteLocation` is always an Azure path which uses the `/` separator.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/796
> Don't use platform specific separator for AzCopy remote location

- src/commands/uploadFiles.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/utils/blobUtils.ts
- src/utils/uploadUtils.ts
This takes care of all the overwrite prompts before any transfers are made.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/757
> Add overwrite prompts for resource uploads

- src/commands/uploadFolder.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/804
> Automatically show folders in Azure tree view after upload

- src/commands/azCopy/IAzCopyResolution.ts
- src/commands/azCopy/azCopyTransfer.ts
- src/commands/uploadFiles.ts
- src/commands/uploadFolder.ts
- src/commands/uploadToAzureStorage.ts
- src/extension.ts
- src/utils/errorUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/817
Here's a few examples of what this looks like in action:
> Continue AzCopy upload after an error occurs

- src/extension.ts
- src/tree/StorageAccountTreeItem.ts
Now these static site commands all display the same error for GPV1 accounts:
Fixes https://github.com/microsoft/vscode-azurestorage/issues/301
> Display 'only GPV2 accounts support hosting' error when disabling site for GPV1 account

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/712
When you open the file explorer in a new window and create a blob in a different window, that blob won't show up in the file explorer because we weren't refreshing the tree item. We were just loading what children existed when the file explorer was opened. So a refresh before calling `treeItem.loadAllChildren` fixes it
> Refresh directory tree item when refreshing the file explorer

- src/AzureStorageFS.ts
Reverts microsoft/vscode-azurestorage#840 since spending more time to fix https://github.com/microsoft/vscode-azurestorage/issues/712 doesn't seem worth it
> Revert "Refresh directory tree item when refreshing the file explorer"

- src/commands/azCopy/azCopyTransfer.ts
I'm not sure how I originally missed this but I did...
Here's an example error message:
> Add missing AzCopy error message

- package-lock.json
- package.json
- src/tree/StorageAccountTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
- src/tree/createWizard/StorageAccountTreeItemCreateStep.ts
- src/tree/createWizard/storageAccountCreateStep.ts
- src/tree/createWizard/storageAccountNameStep.ts
- src/utils/azureClients.ts
- tsconfig.json
Related to https://github.com/microsoft/vscode-azuretools/pull/806
I don't actually think this will help startup performance as much as other extensions, but I want us to use this pattern in all of our extensions regardless. It could also help isolate azure stack changes inside of `createStorageClient`
> Lazy load azure storage package

- src/constants.ts
- src/storageExplorerLauncher/macOSStorageExplorerLauncher.ts
- src/storageExplorerLauncher/windowsStorageExplorerLauncher.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/askOpenInStorageExplorer.ts
If Storage Explorer is required in Linux, an error is still thrown but without an action button to open in SE.
| Mac/Windows | Linux/Codespaces |
| - | - |
| <img width="460" alt="Screen Shot 2021-01-07 at 1 12 00 PM" src="https://user-images.githubusercontent.com/22795803/103945434-0caa7880-50ea-11eb-9c2d-4e2a72b8a715.png">| <img width="460" alt="Screen Shot 2021-01-07 at 1 09 38 PM" src="https://user-images.githubusercontent.com/22795803/103945446-10d69600-50ea-11eb-8c63-8d6660ad16c8.png"> |
Fixes https://github.com/microsoft/vscode-azurestorage/issues/896
> Don't show 'Open resource in Storage Explorer' error action on Linux (Codespaces)

- src/commands/azCopy/azCopyTransfer.ts
The old `excludePath` was only supposed to exclude the .git and .vscode folders but was also excluding .github and .gitignore. So sometimes the number of finished uploads would be less than the total number of files. (the exclude path for total number of files is [here](https://github.com/microsoft/vscode-azurestorage/blob/41888f4c3ee4d632e24f8463c1b20dec765bbf1b/src/utils/uploadUtils.ts#L103))
Here's an example of a directory that has a .gitignore and .github folder:
| Old | New |
|-|-|
| <img width="409" alt="Screen Shot 2021-01-15 at 1 53 28 PM" src="https://user-images.githubusercontent.com/22795803/104782679-79042800-5739-11eb-8e6e-2482d35bb1eb.png">|<img width="409" alt="Screen Shot 2021-01-15 at 1 52 40 PM" src="https://user-images.githubusercontent.com/22795803/104782697-7dc8dc00-5 …
> Make AzCopy excludePath more strict

- README.md
- src/commands/azCopy/azCopyTransfer.ts
Related: https://github.com/microsoft/vscode-azurestorage/issues/917
After looking into it more, I was hesitant to auto-detect this package because you have to use that distro's package manager to query the installed packages. This varies based on the distro and keeping all of those commands up to date sounds like a can 'o worms 🪱
> Show link to wiki when AzCopy fails (with no explanation) on Linux

- src/commands/blob/blobContainerGroupActionHandlers.ts
- src/commands/queue/queueGroupActionHandlers.ts
- src/commands/startEmulator.ts
- src/constants.ts
- src/extension.ts
- src/utils/azuriteUtils.ts
This also adds an install prompt if you try to create an emulated queue or blob container without Azurite installed.
Fixes https://github.com/microsoft/vscode-azurestorage/issues/928
Fixes https://github.com/microsoft/vscode-azurestorage/issues/929
> Update 'must install Azurite' prompt

- .azure-pipelines/common/package.yml
- .azure-pipelines/compliance/compliance.yml
- .azure-pipelines/main.yml
Same as microsoft/vscode-azurefunctions#2769
Since `package.yml` is now run on all OS's, I had to modify the azcopy step a bit to work on Windows. This is probably a good sign because it means the malware scanner will run against the azcopy bits, too.
>  Add AntiMalware Scanner to build

- src/commands/azCopy/azCopyTransfer.ts
`jobInfo.errorMessage` didn't used to be set for this type of failure. This check should cover more unexpected failures than what we were looking for previously. But I wouldn't be surprised if this error message behavior changes again
> Update check for showing 'known issues' link (AzCopy)

- package-lock.json
- package.json
- src/tree/createWizard/storageAccountCreateStep.ts
We can only create Premium storage accounts in EdgeZones, and since we only support Premium Block Blob accounts, I think it makes sense to create this kind of account.
Depends on https://github.com/microsoft/vscode-azuretools/pull/1043
Fixes #1014 #1013
> Create BlockBlob premium accounts for EdgeZones

- package-lock.json
- package.json
- src/AzureStorageFS.ts
- src/utils/azureUtils.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1042
When `findTreeItem` is called. It automatically calls getCachedChildren, but since the StorageTreeItem Proxy isn't resolved yet, it returns an empty array. 
It's being called by AzureFSProvider to get the blob container to display the blob and its contents in the file explorer.  I have a util function that only returns if there is a storage account AppResource attached to the blob/file share and resolves it,  If it is already resolved, it's a no-op so I don't feel too bad about always checking/resolving.
> Resolve storage accounts before trying to find Blob/File children

- package-lock.json
- package.json
- src/extension.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1044
Also move the apiProvder activation in the `extension.activate`
> Directly access the root tree item like a criminal

- CHANGELOG.md
- NOTICE.html
- package-lock.json
- package.json
- Bump version
- Update CHANGELOG
- Update NOTICE
> Release v0.14.1 prep

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1073
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1093
When we changed to T2, I'm pretty sure that the errorTypes changed. Whenever a resource is not found, it throws a "404" rather than the other types that were previously there.
Also, stat would sometimes be called and would call `await fileClient.getProperties();` before we would actually delete the treeItem. 
I'm guessing that this started happening because when we moved to the RG view, rather checking the cache of Storage which is clearewd instantly, we call `await ext.rgApi.appResourceTree.findTreeItem(uriPath, { ...context, loadAll: true });`. I'm guessing RG wasn't clearing the child out fast enough before `stat` was called again.  This made it so …
> Throw FileSystemError on readFile and stat

- src/commands/blob/blobContainerActionHandlers.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/utils/blobUtils.ts
Fixes #970 
These changes do two things:
Yes this is actually allowed by Azure and is even displayed on the Portal.
The result of creating `/a/b/c/test.txt`:
I wanted to still add support for creating unnamed directories in case we allow this down the road for some reason.
> Remove leading slash from user input when creating a blob

- package.json
- src/commands/storageAccountActionHandlers.ts
Fixes #1023 
Added a check when running `Open in Storage Explorer` that checks `remoteName`.  If populated, we warn that the feature is not supported and return..
> Disable 'Open in Storage Explorer' default behavior when in a remote workspace

- extension.bundle.ts
- package.json
- src/AzureStorageFS.ts
- src/commands/blob/blobActionHandlers.ts
- src/commands/deleteFilesAndDirectories.ts
- src/commands/fileShare/directoryActionHandlers.ts
- src/commands/fileShare/fileActionHandlers.ts
- src/extension.ts
- src/tree/blob/BlobTreeItem.ts
- src/utils/directoryUtils.ts
Closes #951 
Closes #1114 
Added support and consolidated the number of `deleteBlob` commands.  Will look into doing something similar for FileShare in the near future... (likely could consolidate most of the delete code into one command but would need to investigate further)
There's two edge cases that I'm covering in this iteration:
<b>Case 1</b>:  If you select multiple items but then right click and delete a different (non-selected) node... 
I decided to model the behavior off of how deleting worked in the normal Windows FS GUI (so basically, only delete the right clicked node when it's not part of the normal selection)
<b>Case 2</b>:  If your selection includes files that are nested in directories of other selections...
To avoid `not found` errors, I check to see if each node is a …
> Add delete many support for blob and fileshare (files/directories)

- package.json
Browsing accounts, creating accounts, etc. still works. Haven't tested everything but I guess declaring limited support is better than being disabled by default.
> Declare limited support for virtual workspaces

- package.json
- src/commands/azCopy/azCopyLocations.ts
- src/commands/downloadFile.ts
- src/commands/downloadFiles/generateSasUrl.ts
- src/commands/downloadFiles/getResourceUri.ts
- src/commands/downloadFiles/getSasToken.ts
- src/commands/registerCommands.ts
- src/commands/storageAccountActionHandlers.ts
- src/tree/IDownloadableTreeItem.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/fileShare/FileTreeItem.ts
- src/utils/copyAndShowToast.ts
- src/utils/uploadUtils.ts
Helps to address https://github.com/microsoft/vscode-azurestorage/issues/998
Specifically 
> A professor provides a link to a data file hosted in Blob Storage
This is something that [Storage Explorer](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/document-translation/create-sas-tokens?tabs=Containers) already does, but the Portal's SAS token generation is lacking.  You can only generate a SAS url for the Blob Container or an individual file. If you paste the container url into the browser, nothing happens. The file url works for downloading in the browser.
File Shares are even worse. There is no SAS token generation. You can download a file by browsing to it in the portal, but it's definitely using a SAS token as well.
Technically, the SAS token can be appended to …
> Add command to get SAS url for Blobs/FileShares

- src/commands/deleteBlobDirectory/DeleteBlobDirectoryStep.ts
We shouldn't show activity success messages as information messages when this setting is true (default).
> Respect suppress notification setting when deleting blob directory

- package.json
This reverts commit bcab9fdff1a5718bd945f23f32cdf510824562ae.
Fixes #1131 
We will make this change again once RGs has been released.
> Revert "Use new AzExtResourceType context values"

- src/utils/uploadUtils.ts
Found this issue while testing: 
When adding a folder to a blob container a sub directory called "*" was added. 
Link to original PR: https://github.com/microsoft/vscode-azurestorage/pull/1151
> Fixed issue found from downloading from a Sas url... code integration 

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/377
Due to https://github.com/microsoft/vscode-azureresourcegroups/commit/17033f24577c52ba19af7188f5169f598423b6ee, the id of the GroupTreeItems changed on every Azure Group Tree Item.  That changed the form of expected id, which AzureStorageFS needs to look up tree items in the tree view.
This is changing the regexp to match the new expected id form.
> Fix the regExp that matches the id of the tree item

- src/AzureStorageFS.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1162
Since the format of our ID changes depending on the grouping (resource type, resource group, etc.), I think it's safer to just use a wildcard capture on it. There's still quite a bit of safety since the rest of the id has to match, and that format is pretty specific. It is just wildcarding the group portion of the id.
This happened because the ids for group typing used to be `provider/type.kind` but got switched to just `AzExtResourceType`.
> Use wildcard regex instead of exact format of id

- package.json
Expanded fix for #1023 
Previously only did the fix for the storage account node itself
> Remove `open in storage explorer` option on remote for all other tree items

- src/commands/downloadFile.ts
- src/commands/downloadFiles/DownloadFilesStep.ts
- src/commands/downloadFiles/IDownloadWizardContext.ts
Closes #1163 
Added an activity context to the Azure Wizard for downloading files.  As per our standup discussion, wiring this up to the activity log will serve as the notification for completion of the download activity instead of an information window pop-up.  We can expand upon this implementation if we find more information needs to be displayed later.
> Add activity context to downloadFiles wizard

- src/tree/blob/BlobContainerGroupTreeItem.ts
- src/tree/blob/createBlobContainer/BlobContainerNameStep.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1161
This is more of a temporary fix for the release. Eventually, we'd want the entire process to be a wizard so it can be integrated with the activity log. Also there is a lot of copy/pasted code between the name validation between blob containers and file shares that can be reused, so we should refactor for that as well.
But this was the quickest solution for this current issue, so just went ahead and accomplished that.
> Refactor for BlobContainerNameStep

- src/tree/table/TableGroupTreeItem.ts
Fixes this TS error:
`
Property 'parent' will overwrite the base property in 'AzExtParentTreeItem'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.ts(2612)
`
> Intentionally override base property

- src/tree/StorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1198
I added this in https://github.com/microsoft/vscode-azurestorage/pull/1196 because at the time `isAncestorOf` wasn't supported by the compat shim.  It's being added in https://github.com/microsoft/vscode-azuretools/pull/1368.
> Remove `pickTreeItemImpl`

- src/commands/commonTreeCommands.ts
- src/commands/storageAccountActionHandlers.ts
If you're picking a top level Azure resource, you cannot pass in an expected child context value. The compat API doesn't support this.
I think this was a mistake made in v1, but v1 just so happen to be fine with it. We need to make sure we don't do this in v1.5.
Fixes #1202
> Fix delete storage account from palette

- .azure-pipelines/common/package.yml
The builds were breaking whenever `npm list --production --parseable --depth=99999 --loglevel=error` ran. This was because forcing azcopy to install on an OS it doesn't support was throwing invalid errors. 
For example, this is for Windows:
```
npm ERR! code ELSPROBLEMS
> vscode-azurestorage@0.15.4-alpha.0 package
npm ERR! invalid: @azure-tools/azcopy-darwin@10.19.0 D:\a\1\s\node_modules\@azure-tools\azcopy-darwin
> vsce package --githubBranch main
npm ERR! invalid: @azure-tools/azcopy-linux@10.19.0 D:\a\1\s\node_modules\@azure-tools\azcopy-linux
```
> Create different "Install azcopy" steps based on OS Agent

- src/commands/downloadFile.ts
- src/commands/downloadFiles/DownloadFilesStep.ts
- src/commands/transfers/transfers.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/utils/fs.ts
- src/utils/uploadUtils.ts
- Create functions for uploading files & folders in `tranfers.ts`
- Bring consistency to parameters in `transfers.ts`
- Remove remaining references to `azcopy-node` outside of transfers.ts and AzCopy specific files
> Create transfer-tech agnostic functions for upload

- src/AzureStorageFS.ts
- src/utils/blobUtils.ts
Fixes #1286 
Previously, trying to view the blobs in an emulated blob container by opening a new explorer window would error when loading said blobs. This is resolved by using `client.downloadToBuffer()` similar to what is done in `readFile()` of BlobContainerFS.ts instead of manually handling and reading the chunks of the stream.
Also, dragging and dropping files into the explorer of an emulated blob container was not behaving as expected because `writeFile()` inside `AzureStorageFS.ts` which handles writing operations for emulated containers (opened in a new explorer window) creates an empty text file for newly created blobs. This fix passes along the blob contents to the existing `containerClient` calls where we perform blob uploads.
> Simplify AzureStorageFS readFile and pass along contents when creating a new blob in writeFile

- package.json
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1262
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1261
So this is the "easiest" way to do this, but it's also probably one of the ugliest...
We may be able to just add templates steps to do this, but it's also a one-off solution, so I feel okay just running the command via `npm run package`.
vsce package --no-dependencies is required to ignore all the errors caused by having OS specific packages on the wrong OS. Ideally, we could have 3 separate extensions for each OS runtime, but unless we're doing this via a pipeline, I don't feel comfortable making it part of the manual release process.
Note, we have been shipping a vsix with all 3 versions for years without issue.
> Edit the package script to install all versions of azcopy

- src/tree/blob/BlobTreeItem.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/utils/blobUtils.ts
Fix #1349 
Basically fixed the `resourceUri` so that we reference the parent (File Share or Blob Container) URI which is what the old implementation expects to work properly.
I tried downloading all combinations of the files/folders below and it is working again... if you can think of anything else to try let me know.
> Fix downloading from File Shares and Blob Containers

- .azure-pipelines/1esmain.yml
- .github/workflows/main.yml
- package.json
It's better to do this as a build step rather than a preinstall script so it doesn't impact local development.
> Install azcopy in build pipeline

- src/tree/StorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1298
We can't just write it as a data property because the Resource Groups extension doesn't update the data property on the node when it resolves resources from other extensions.  By using the `getData` property instead, it will recognize that there's a new property from the storage resolver and use that instead.
Kind of a wonky workaround until we ever migrate everything to v2.
> Add viewProperties model to get full data of storage account

- src/constants.ts
- src/tree/AttachedStorageAccountTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1385
The sdk recognized `UseDevelopmentStorage=true` as a native connection string, however that would limit users to only being able to use the default host and port.
This will read Azurite's settings and use those if they exist.
> Use azurite settings for listening to emulator

- src/AzureStorageFS.ts
- src/tree/blob/BlobContainerTreeItem.ts
- src/tree/blob/BlobDirectoryTreeItem.ts
- src/tree/blob/BlobTreeItem.ts
- src/tree/fileShare/DirectoryTreeItem.ts
- src/tree/fileShare/FileShareTreeItem.ts
- src/tree/fileShare/FileTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1394
This was occurring for blobs, blob containers, file shares, and files, not just blobs like the issue indicates.
> Manually refresh whenever fireDeleteEvent happens in workspace view

- src/tree/blob/BlobContainerGroupTreeItem.ts
- Attached storage accounts can create blob containers without errors
- Azure subscription storage accounts continue to work as before
Fixes #1411
> Fix blob container creation for attached storage accounts
